name: HubTransfer
author: SigitGamers
api: [3.0.0, 4.0.0]
version: 1.0 premi
main: SigitGamers\Main
depend: 
- TransferAPI

commands:
  lobby:
     usage: /lobby
     aliases: [lobby, hub, spawn]
     description: §oTransfering You to Lobby Server

