name: HubTransfer
author: SigitGamersYT
api: [3.0.0, 4.0.0]
version: 1.0 premi
main: SigitGamersYT\HubTransfer\Main

commands:
  lobby:
     usage: /lobby
     aliases: [lobby, hub, spawn]
     description: §oTransfer to Server Lobby
